---
apiVersion: v1
kind: Pod  # this is the object to be created by k8s
metadata:
  name: nginx    # name of our pod
spec:
  containers:
  - name: nginx  # name of a container
    image: nginx:1.7.9     # name and version of image to use
    ports:
    - containerPort: 80

