apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 2
  template:
    metadata:
      labels: 
        app: webby
    spec:
      containers:
      - name: webby
        image: reg.alta3.com/15-caccamo-webby
        ports: 
        - containerPort: 80
